name: flutter_architecture
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  configuration:
    path: ./configuration
  cupertino_icons: ^1.0.2
  flutter_bloc: ^7.3.0
  cached_network_image: ^3.2.0
  equatable: ^2.0.3
  pedantic: ^1.11.1
  flutter_screenutil: ^5.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: any
  mockito: ^5.0.10
  bloc_test: ^8.0.0
  flutter_lints: ^1.0.0
  build_runner: ^2.1.7
  json_serializable: ^6.1.4
  flutter_native_splash: ^1.2.1
  flutter_launcher_icons: ^0.9.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: SvnGilroy
      fonts:
        - asset: assets/fonts/SVNGilroyBlack.otf
        - asset: assets/fonts/SVNGilroyBlackItalic.otf
        - asset: assets/fonts/SVNGilroyBold.otf
        - asset: assets/fonts/SVNGilroyBoldItalic.otf
        - asset: assets/fonts/SVNGilroyHeavy.otf
        - asset: assets/fonts/SVNGilroyHeavyItalic.otf
        - asset: assets/fonts/SVNGilroyItalic.otf
        - asset: assets/fonts/SVNGilroyLight.otf
        - asset: assets/fonts/SVNGilroyLightItalic.otf